import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCareAIToolAuthorityEvaluator as create} from './veteran-care-ai-tool-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[];
  const evaluate=create({toolClock:()=>1500000,getCurrentAIToolPolicy:async()=>policy(),resolveVerifiedAIToolProposal:async q=>({verified:true,...q}),decisionClock:()=>1500000,getAICallerRegistration:async()=>({foundationAppId:appId,aiCallerId:'shine-veteran-care',targetServiceAppId:'shine.ai',status:'active',revision:1,keyId:'vc-adj-v1'}),resolveVerifiedAICallerProof:async q=>({verified:true,proofRef:q.proofRef,foundationAppId:appId,actorShineId:shineId,appId:'shine-veteran-care',keyId:'vc-adj-v1'}),appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls};
}
const joined=()=>({authContext:input().authContext,aiCallerProof:{proofRef:sessionId},purposeContext:{preparationId},toolCall:{toolCallId:preparationId,toolId:'veteran-care.selected_record_read',arguments:{recordId,recordVersion:3}}});
const policy=()=>({status:'active',foundationAppId:appId,aiCallerId:'shine-veteran-care',targetServiceAppId:'shine.ai',toolId:'veteran-care.selected_record_read',capabilityId:'veteran-care.selected_record_read',scope,operation:'read',purpose,policyRevision:1,validUntil:end});
test('verified exact proposed tool returns immutable scope evidence without invocation',async()=>{const r=await fixture().evaluate(joined());assert.equal(r.status,'tool-scope-approved');assert.equal(r.envelope.contract,'shine-foundation/veteran-care-ai-tool-authority-v1');assert.equal(r.executionPermitted,false);assert.equal(r.toolInvoked,false);assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.envelope.toolId,'veteran-care.selected_record_read');assert.equal(r.envelope.toolCallId,preparationId);assert.equal(r.envelope.toolPolicyRevision,1);assert.equal(r.envelope.resourceId,recordId);assert.ok(Object.isFrozen(r.envelope));assert.equal(JSON.stringify(r).includes('synthetic'),false);});
test('unknown write memory and broad model-selected tools stop before policy lookup',async()=>{for(const change of [q=>q.toolCall.toolId='record.write',q=>q.toolCall.toolId='memory.search',q=>q.toolCall.arguments.query='all',q=>q.toolCall.arguments.recordId='*',q=>q.toolCall.arguments.ownerShineId=shineId,q=>q.toolCall.executionPermitted=true]){let calls=0;const q=joined();change(q);const r=await fixture({options:{getCurrentAIToolPolicy:async()=>{calls++;return policy();}}}).evaluate(q);assert.equal(r.envelope,undefined);assert.equal(calls,0);}});
test('unverified caller and absent record consent cannot reach AI tool policy',async()=>{for(const options of [{resolveVerifiedAICallerProof:async()=>null},{getPermissionContext:async()=>({...context(),grants:[]})}]){let calls=0;const f=fixture({options:{...options,getCurrentAIToolPolicy:async()=>{calls++;return policy();}}});assert.equal((await f.evaluate(joined())).envelope,undefined);assert.equal(calls,0);}});
test('closed mismatched tool policy or invalid revision withholds envelope',async()=>{for(const [key,value] of [['status','disabled'],['foundationAppId','shine.travel'],['aiCallerId','shine-fish'],['targetServiceAppId','other'],['toolId','*'],['capabilityId','write'],['scope','*'],['operation','write'],['purpose','general-chat'],['policyRevision',0]])assert.equal((await fixture({options:{getCurrentAIToolPolicy:async()=>({...policy(),[key]:value})}}).evaluate(joined())).envelope,undefined);});
test('verified proposal must correlate call arguments actor key purpose and signed request',async()=>{for(const key of ['verified','toolCallId','recordId','recordVersion','actorShineId','keyId','callerProofRef','preparationId'])assert.equal((await fixture({options:{resolveVerifiedAIToolProposal:async q=>({verified:true,...q,[key]:'wrong'})}}).evaluate(joined())).envelope,undefined);});
test('grant withdrawal during proposal verification defeats initial decision',async()=>{const snapshot=context(),f=fixture({snapshot,options:{resolveVerifiedAIToolProposal:async q=>{snapshot.grants[0].status='revoked';return {verified:true,...q};}}});assert.equal((await f.evaluate(joined())).envelope,undefined);});
test('policy withdrawal revision or deadline change during evaluation cannot inherit approval',async()=>{for(const [key,value] of [['status','disabled'],['policyRevision',2],['validUntil','1970-01-01T00:32:00.000Z']]){let calls=0;assert.equal((await fixture({options:{getCurrentAIToolPolicy:async()=>({...policy(),...(calls++?{[key]:value}:{})})}}).evaluate(joined())).envelope,undefined);}});
test('tool policy expiry bounds validity and expiry during waits refuses',async()=>{const validUntil='1970-01-01T00:30:00.000Z';const r=await fixture({options:{getCurrentAIToolPolicy:async()=>({...policy(),validUntil})}}).evaluate(joined());assert.equal(r.envelope.validUntil,validUntil);let clock=1500000;const f=fixture({options:{toolClock:()=>clock,resolveVerifiedAIToolProposal:async q=>{clock=2000000;return {verified:true,...q};}}});assert.equal((await f.evaluate(joined())).envelope,undefined);});
test('authority outages and input accessors reveal no private errors',async()=>{for(const key of ['getCurrentAIToolPolicy','resolveVerifiedAIToolProposal']){const r=await fixture({options:{[key]:async()=>{throw Error('private');}}}).evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.envelope,undefined);assert.equal(JSON.stringify(r).includes('private'),false);}const q=joined();Object.defineProperty(q.toolCall.arguments,'recordId',{get(){throw Error('getter');}});assert.equal((await fixture().evaluate(q)).envelope,undefined);});
test('proposal mutation during awaits cannot alter captured exact record selection',async()=>{const q=joined(),pending=fixture().evaluate(q);q.toolCall.arguments.recordId=preparationId;q.toolCall.toolCallId=recordId;const r=await pending;assert.equal(r.envelope.resourceId,recordId);assert.equal(r.envelope.toolCallId,preparationId);});
