import test from 'node:test';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {createVeteranCareCheckpointFailureGate as create} from './veteran-care-checkpoint-failure-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  let stored=checkpoint();const writes=[];const calls=[],reads=[],registry=new Map([[sessionId,retryRow()]]);
  const evaluate=create({checkpointClock:()=>1500000,commitResumeCheckpoint:async q=>{writes.push(q);assert.equal(stored.revision,q.expectedRevision);stored=q.checkpoint;return {status:'committed',checkpoint:stored};},resumeClock:()=>1500000,getCurrentResumeCheckpoint:async()=>stored,getExistingRetryIdentity:async q=>registry.get(q.operationId),taskClock:()=>1500000,getCurrentVCTask:async()=>task(),audienceClock:()=>1500000,verifyResultRecipient:async()=>recipient(),releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads,registry,writes};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({checkpointId:preparationId,recipientAuthContext:{serviceToken:'synthetic-recipient'},authContext:input().authContext,companionAuthContext:{clientToken:'synthetic-client',userToken:'synthetic-user'}});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
const recipient=()=>({verified:true,audience:'vc-trusted-server',appId,actorShineId:shineId,servicePrincipalId:'vc-orchestrator',revision:1,validUntil:end});
const task=()=>({taskId:grantId,foundationAppId:appId,ownerShineId:shineId,memoryId:recordId,memoryVersion:3,preparationId,purpose,operation:'read',status:'running',revision:1,validUntil:end});
const checkpoint=()=>({checkpointId:preparationId,foundationAppId:appId,ownerShineId:shineId,operationId:sessionId,taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,stage:'selected-memory-read',status:'resumable',revision:1,validUntil:end});
function retryRow(){const binding={foundationAppId:appId,actorShineId:shineId,clientId:'shine.companion',taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,operation:'read',scope:'veteran-care.memory.read',purpose,audience:'vc-trusted-server'};return {operationId:sessionId,fingerprint:createHash('sha256').update(JSON.stringify(binding)).digest('hex'),binding};}
test('confirmed atomic checkpoint records progress but releases no private result or resume permission',async()=>{const f=fixture(),r=await f.evaluate(joined());assert.equal(r.status,'checkpoint-confirmed');assert.equal(r.durableProgressConfirmed,true);assert.equal(r.checkpoint.revision,2);assert.equal(r.result,undefined);assert.equal(r.resultReturned,false);assert.equal(r.resumePermitted,false);assert.equal(r.requiresFreshResumeCheck,true);assert.equal(f.reads.length,1);assert.equal(f.writes.length,1);assert.ok(Object.isFrozen(f.writes[0]));assert.ok(Object.isFrozen(f.writes[0].checkpoint));assert.ok(Object.isFrozen(r.checkpoint));const serialized=JSON.stringify(f.writes);assert.equal(serialized.includes('synthetic'),false);assert.equal(serialized.includes('serviceToken'),false);assert.equal(serialized.includes('content'),false);});
test('write failure after private read withholds content and does not retry',async()=>{let calls=0;const f=fixture({options:{commitResumeCheckpoint:async()=>{calls++;throw Error('private credential');}}}),r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.retrievalPerformed,true);assert.equal(r.checkpointWriteAttempted,true);assert.equal(r.writeOutcome,'unconfirmed');assert.equal(r.durableProgressConfirmed,false);assert.equal(r.resumePermitted,false);assert.equal(r.result,undefined);assert.equal(calls,1);assert.equal(JSON.stringify(r).includes('credential'),false);});
test('false missing mismatched and extra-field commit acknowledgements are never durable success',async()=>{for(const reply of [q=>null,q=>({status:'conflict',checkpoint:q.checkpoint}),q=>({status:'committed',checkpoint:{...q.checkpoint,revision:1}}),q=>({status:'committed',checkpoint:q.checkpoint,durable:true})]){let commits=0,lookups=0;const f=fixture({options:{getCurrentResumeCheckpoint:async()=>{lookups++;return checkpoint();},commitResumeCheckpoint:async q=>{commits++;return reply(q);}}}),r=await f.evaluate(joined());assert.equal(r.durableProgressConfirmed,false);assert.equal(r.result,undefined);assert.equal(commits,1);assert.equal(lookups,3);}});
test('acknowledgement alone cannot prove authoritative storage',async()=>{for(const change of [c=>({...c,revision:1}),c=>({...c,revision:3}),c=>({...c,status:'superseded'}),c=>({...c,memoryVersion:4})]){let stored=checkpoint();const f=fixture({options:{getCurrentResumeCheckpoint:async()=>stored,commitResumeCheckpoint:async q=>{stored=change({...q.checkpoint});return {status:'committed',checkpoint:q.checkpoint};}}});const r=await f.evaluate(joined());assert.equal(r.durableProgressConfirmed,false);assert.equal(r.result,undefined);}});
test('timeout after committed write remains ambiguous without automatic duplicate write',async()=>{let stored=checkpoint(),commits=0;const f=fixture({options:{getCurrentResumeCheckpoint:async()=>stored,commitResumeCheckpoint:async q=>{commits++;stored=q.checkpoint;throw Error('timeout');}}}),r=await f.evaluate(joined());assert.equal(stored.revision,2);assert.equal(r.writeOutcome,'unconfirmed');assert.equal(r.durableProgressConfirmed,false);assert.equal(commits,1);});
test('readback outage and accessor response are withheld and redacted',async()=>{for(const mode of ['outage','accessor']){let saved=false;const f=fixture({options:{getCurrentResumeCheckpoint:async()=>{if(saved)throw Error('private row');return checkpoint();},commitResumeCheckpoint:async q=>{saved=true;if(mode==='outage')return {status:'committed',checkpoint:q.checkpoint};return {status:'committed',get checkpoint(){throw Error('getter');}};}}});const r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.durableProgressConfirmed,false);assert.equal(JSON.stringify(r).includes('private'),false);}});
test('cancelled task withdrawn consent and missing retry never write checkpoints',async()=>{for(const options of [{getCurrentVCTask:async()=>({...task(),status:'cancelled'})},{getMemoryPermissionContext:async()=>({...consent(),grants:[]})},{getExistingRetryIdentity:async()=>null}]){const f=fixture({options}),r=await f.evaluate(joined());assert.equal(r.durableProgressConfirmed,false);assert.equal(r.checkpointWriteAttempted,false);assert.equal(f.writes.length,0);assert.equal(f.reads.length,0);}});
test('expired deadline or invalid regressing clock prevents commit or confirmation',async()=>{for(const late of [2000000,1499999,NaN]){let clock=1500000;const f=fixture({options:{checkpointClock:()=>clock,readSelectedMemory:async()=>{clock=late;return row();}}});const r=await f.evaluate(joined());assert.equal(r.durableProgressConfirmed,false);assert.equal(f.writes.length,0);}});
test('deadline reached during commit cannot report confirmed progress',async()=>{let clock=1500000,stored=checkpoint();const f=fixture({options:{checkpointClock:()=>clock,getCurrentResumeCheckpoint:async()=>stored,commitResumeCheckpoint:async q=>{stored=q.checkpoint;clock=2000000;return {status:'committed',checkpoint:stored};}}}),r=await f.evaluate(joined());assert.equal(r.durableProgressConfirmed,false);assert.equal(r.writeOutcome,'unconfirmed');});
test('revision overflow and caller content authority or next revision are refused',async()=>{const f=fixture({options:{getCurrentResumeCheckpoint:async()=>({...checkpoint(),revision:Number.MAX_SAFE_INTEGER})}});assert.equal((await f.evaluate(joined())).checkpointWriteAttempted,false);for(const change of [q=>q.checkpoint=checkpoint(),q=>q.revision=99,q=>q.result=row(),q=>q.permission={decision:'allow'}]){const q=joined();change(q);const f=fixture();assert.equal((await f.evaluate(q)).durableProgressConfirmed,false);assert.equal(f.writes.length,0);}});
test('concurrent checkpoint saves use compare-and-swap and only one confirms revision',async()=>{const f=fixture(),rs=await Promise.all([f.evaluate(joined()),f.evaluate(joined())]);assert.equal(rs.filter(r=>r.durableProgressConfirmed).length,1);assert.equal(f.writes.length,2);assert.deepEqual(f.writes.map(q=>q.expectedRevision),[1,1]);assert.ok(rs.every(r=>!r.resumePermitted&&r.result===undefined));});
test('input and adapter row mutations cannot replace captured selection',async()=>{const q=joined(),f=fixture(),pending=f.evaluate(q);q.checkpointId=recordId;const r=await pending;assert.equal(r.checkpoint.checkpointId,preparationId);assert.equal(f.writes[0].checkpoint.memoryId,recordId);});
