import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCareReadOnlyMemoryRetriever as create} from './veteran-care-memory-read-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[],reads=[];
  const evaluate=create({releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({authContext:input().authContext,companionAuthContext:{clientToken:'synthetic-client',userToken:'synthetic-user'},request:{operation:'read',memoryId:recordId,memoryVersion:3,preparationId}});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
test('one selected read returns immutable content only to trusted VC orchestration',async()=>{const f=fixture(),r=await f.evaluate(joined());assert.equal(r.status,'private-memory-read-ready');assert.equal(r.result.content,'synthetic private memory');assert.equal(r.audience,'vc-trusted-server');assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.memoryWritePermitted,false);assert.equal(r.requiresFreshDisclosureCheck,true);assert.ok(Object.isFrozen(r.result));assert.equal(f.reads.length,1);assert.equal(f.reads[0].ownerShineId,shineId);assert.equal(f.reads[0].memoryVersion,3);assert.equal(f.reads[0].operation,'read');assert.ok(Object.isFrozen(f.reads[0]));assert.equal(JSON.stringify(f.reads).includes('synthetic'),false);assert.equal(f.calls.length,4);});
test('writes searches owner selection and accessor inputs never invoke content adapter',async()=>{for(const change of [q=>q.request.operation='write',q=>q.request.memoryId='*',q=>q.request.query='all',q=>q.ownerShineId=shineId,q=>Object.defineProperty(q.request,'memoryVersion',{get(){throw Error('getter');}})]){const q=joined();change(q);const f=fixture(),r=await f.evaluate(q);assert.equal(r.resultReturned,false);assert.equal(f.reads.length,0);}});
test('unverified user or missing consent withholds content before retrieval',async()=>{for(const options of [{verifyCompanionUser:async()=>({verified:false,clientId:'shine.companion',shineId})},{getMemoryPermissionContext:async()=>({...consent(),grants:[]})}]){const f=fixture({options});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('returned owner memory version category and extra data must exactly match',async()=>{for(const [key,value] of [['ownerShineId',sessionId],['memoryId',preparationId],['memoryVersion',4],['category','family'],['otherMemory','private']]){const r=await fixture({options:{readSelectedMemory:async()=>({...row(),[key]:value})}}).evaluate(joined());assert.equal(r.result,undefined);assert.equal(r.resultReturned,false);}});
test('non-text empty oversized and accessor content are withheld',async()=>{for(const content of ['', 'x'.repeat(16385),{},['private'],null])assert.equal((await fixture({options:{readSelectedMemory:async()=>({...row(),content})}}).evaluate(joined())).result,undefined);let invoked=0;const r=await fixture({options:{readSelectedMemory:async()=>Object.defineProperty(row(),'content',{get(){invoked++;return 'private';}})}}).evaluate(joined());assert.equal(r.result,undefined);assert.equal(invoked,0);});
test('withdrawal during private read prevents final result release',async()=>{const c=consent();const f=fixture({options:{getMemoryPermissionContext:async()=>c,readSelectedMemory:async()=>{c.grants[0].status='revoked';return row();}}});const r=await f.evaluate(joined());assert.equal(r.retrievalPerformed,true);assert.equal(r.resultReturned,false);assert.equal(r.result,undefined);});
test('current revision link and grant replacement during read cannot inherit first decision',async()=>{for(const kind of ['revision','link','grant']){let read=false;const f=fixture({options:{getMemoryPermissionContext:async()=>{const c=consent();if(read&&kind==='revision')c.revision=2;if(read&&kind==='grant')c.grants[0].grantId=preparationId;return c;},getCurrentMemoryPermissionRevision:async()=>({...revision(),revision:read&&kind==='revision'?2:1}),getCurrentVCCompanionLink:async()=>({...link(),status:read&&kind==='link'?'revoked':'active'}),readSelectedMemory:async()=>{read=true;return row();}}});assert.equal((await f.evaluate(joined())).result,undefined);}});
test('release expiry clock failure or regression withholds prepared content',async()=>{for(const late of [2000000,1499999,NaN]){let clock=1500000;const f=fixture({options:{releaseClock:()=>clock,readSelectedMemory:async()=>{clock=late;return row();}}});assert.equal((await f.evaluate(joined())).result,undefined);}});
test('adapter and final authority failures return no private exception details',async()=>{const f=fixture({options:{readSelectedMemory:async()=>{throw Error('synthetic private memory');}}});const r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.result,undefined);assert.equal(JSON.stringify(r).includes('synthetic private memory'),false);let read=false;const g=fixture({options:{readSelectedMemory:async()=>{read=true;return row();},getMemoryPermissionContext:async()=>{if(read)throw Error('private');return consent();}}});assert.equal((await g.evaluate(joined())).result,undefined);});
test('request and adapter result mutations during awaits do not alter captured selection/content',async()=>{const q=joined(),source=row();let contexts=0;const f=fixture({options:{readSelectedMemory:async()=>source,getMemoryPermissionContext:async()=>{if(contexts++)source.content='changed after read';return consent();}}});const pending=f.evaluate(q);q.request.memoryId=preparationId;q.request.memoryVersion=9;const r=await pending;assert.equal(r.status,'private-memory-read-ready');assert.equal(r.result.memoryId,recordId);assert.equal(r.result.memoryVersion,3);assert.equal(r.result.content,'synthetic private memory');assert.equal(source.content,'changed after read');});
