import test from 'node:test';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {createVeteranCareCredentialReferenceGate as create} from './veteran-care-credential-reference-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const refs=[],resolutions=[];const calls=[],reads=[],registry=new Map([[sessionId,retryRow()]]);
  const evaluate=create({credentialClock:()=>1500000,getCurrentCredentialReference:async q=>{refs.push(q);return reference();},resolveCredentialReference:async q=>{resolutions.push(q);return credentials();},resumeClock:()=>1500000,getCurrentResumeCheckpoint:async()=>checkpoint(),getExistingRetryIdentity:async q=>registry.get(q.operationId),taskClock:()=>1500000,getCurrentVCTask:async()=>task(),audienceClock:()=>1500000,verifyResultRecipient:async()=>recipient(),releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads,registry,refs,resolutions};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({checkpointId:preparationId,credentialReferenceId:grantId,authContext:input().authContext});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
const recipient=()=>({verified:true,audience:'vc-trusted-server',appId,actorShineId:shineId,servicePrincipalId:'vc-orchestrator',revision:1,validUntil:end});
const task=()=>({taskId:grantId,foundationAppId:appId,ownerShineId:shineId,memoryId:recordId,memoryVersion:3,preparationId,purpose,operation:'read',status:'running',revision:1,validUntil:end});
const checkpoint=()=>({checkpointId:preparationId,foundationAppId:appId,ownerShineId:shineId,operationId:sessionId,taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,stage:'selected-memory-read',status:'resumable',revision:1,validUntil:end});
function retryRow(){const binding={foundationAppId:appId,actorShineId:shineId,clientId:'shine.companion',taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,operation:'read',scope:'veteran-care.memory.read',purpose,audience:'vc-trusted-server'};return {operationId:sessionId,fingerprint:createHash('sha256').update(JSON.stringify(binding)).digest('hex'),binding};}
const reference=()=>({credentialReferenceId:grantId,foundationAppId:appId,ownerShineId:shineId,purpose:'veteran-care.resume',audience:'vc-trusted-server',status:'active',revision:1,validUntil:end});
const credentials=()=>({credentialReferenceId:grantId,revision:1,companionAuthContext:{clientToken:'vault-client-secret',userToken:'vault-user-secret'},recipientAuthContext:{serviceToken:'vault-service-secret'}});
test('opaque reference resolves internally and still runs the actual fresh resume pipeline',async()=>{const f=fixture(),r=await f.evaluate(joined());assert.equal(r.status,'credential-reference-result');assert.equal(r.credentialsReturned,false);assert.equal(r.requiresFreshCredentialResolution,true);assert.equal(r.retry.authorityRechecked,true);assert.equal(r.checkpointAuthorityReused,false);assert.equal(f.reads.length,1);assert.equal(f.resolutions.length,1);assert.equal(f.refs.length,3);assert.ok(Object.isFrozen(r.credentialReference));assert.ok(Object.isFrozen(f.resolutions[0]));for(const v of Object.values(credentials().companionAuthContext).concat(credentials().recipientAuthContext.serviceToken)){assert.equal(JSON.stringify(r).includes(v),false);assert.equal(JSON.stringify(f.resolutions).includes(v),false);}assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.transportPerformed,false);});
test('missing revoked wrong-owner app purpose audience and malformed reference stop before resolution',async()=>{for(const r of [null,{},...Object.entries({credentialReferenceId:recordId,status:'revoked',ownerShineId:recordId,foundationAppId:'shine.travel',purpose:'model-disclosure',audience:'shine.ai',revision:0,validUntil:'bad'}).map(([k,v])=>({...reference(),[k]:v}))]){const f=fixture({options:{getCurrentCredentialReference:async()=>r}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.resolutions.length,0);assert.equal(f.reads.length,0);}});
test('wrong resolution identity revision credential shapes and accessors grant no read',async()=>{for(const r of [null,{...credentials(),credentialReferenceId:recordId},{...credentials(),revision:2},{...credentials(),recipientAuthContext:{serviceToken:''}},{...credentials(),companionAuthContext:{clientToken:'secret',userToken:'secret',permission:true}},{...credentials(),get revision(){throw Error('getter');}}]){const f=fixture({options:{resolveCredentialReference:async()=>r}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('reference never substitutes for current VC session Companion user recipient task or consent',async()=>{for(const options of [{getSessionState:async()=>({status:'revoked'})},{verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId:recordId})},{verifyResultRecipient:async()=>({...recipient(),actorShineId:recordId})},{getCurrentVCTask:async()=>({...task(),status:'cancelled'})},{getMemoryPermissionContext:async()=>({...consent(),grants:[]})}]){const f=fixture({options});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('rotation or revocation before private read stops actual adapter invocation',async()=>{for(const changed of [{revision:2},{status:'revoked'}]){let n=0;const f=fixture({options:{getCurrentCredentialReference:async()=>({...reference(),...(n++?changed:{})})}}),r=await f.evaluate(joined());assert.equal(r.retrievalPerformed,false);assert.equal(r.result,undefined);assert.equal(f.reads.length,0);}});
test('reference withdrawal after read withholds already prepared content',async()=>{let n=0;const f=fixture({options:{getCurrentCredentialReference:async()=>({...reference(),status:n++>=2?'revoked':'active'})}}),r=await f.evaluate(joined());assert.equal(r.retrievalPerformed,true);assert.equal(r.result,undefined);});
test('each use resolves fresh rotated credentials rather than caching secrets or authority',async()=>{let revision=1,secret='first';const tokens=[];const f=fixture({options:{getCurrentCredentialReference:async()=>({...reference(),revision}),resolveCredentialReference:async()=>({...credentials(),revision,companionAuthContext:{clientToken:'client',userToken:secret}}),verifyCompanionUser:async q=>{tokens.push(q.authContext.userToken);return {verified:true,clientId:'shine.companion',shineId};}}});const a=await f.evaluate(joined());revision=2;secret='second';const b=await f.evaluate(joined());assert.equal(a.credentialReference.revision,1);assert.equal(b.credentialReference.revision,2);assert.ok(tokens.includes('first'));assert.ok(tokens.includes('second'));assert.equal(f.reads.length,2);assert.equal(JSON.stringify(b).includes('second'),false);});
test('reference deadline bounds output while expiry and regressing clocks deny',async()=>{const validUntil='1970-01-01T00:30:00.000Z',r=await fixture({options:{getCurrentCredentialReference:async()=>({...reference(),validUntil})}}).evaluate(joined());assert.equal(r.recipient.validUntil,validUntil);assert.equal(r.checkpoint.validUntil,validUntil);for(const late of [2000000,1499999,NaN]){let clock=1500000;const f=fixture({options:{credentialClock:()=>clock,resolveCredentialReference:async()=>{clock=late;return credentials();}}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('caller raw credentials authority URLs and accessors cannot override a reference',async()=>{for(const change of [q=>q.companionAuthContext=credentials().companionAuthContext,q=>q.recipientAuthContext=credentials().recipientAuthContext,q=>q.permission={decision:'allow'},q=>q.credentialReferenceId='https://vault/secret',q=>Object.defineProperty(q,'credentialReferenceId',{get(){throw Error('getter');}})]){const q=joined();change(q);const f=fixture();assert.equal((await f.evaluate(q)).result,undefined);assert.equal(f.resolutions.length,0);}});
test('input reference and credentials are captured before async verification',async()=>{const q=joined(),f=fixture(),pending=f.evaluate(q);q.credentialReferenceId=recordId;q.authContext.appToken='changed';const r=await pending;assert.equal(r.credentialReference.credentialReferenceId,grantId);assert.equal(f.resolutions[0].credentialReferenceId,grantId);});
test('vault and reference outages fail closed without secret error details',async()=>{for(const key of ['getCurrentCredentialReference','resolveCredentialReference']){const f=fixture({options:{[key]:async()=>{throw Error('vault-secret');}}}),r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.result,undefined);assert.equal(JSON.stringify(r).includes('vault-secret'),false);assert.equal(f.reads.length,0);}});
test('resolved secret object mutation cannot change captured credentials during downstream awaits',async()=>{const c=credentials();let received,count=0;const f=fixture({options:{resolveCredentialReference:async()=>c,getSessionState:async()=>{if(count++)c.companionAuthContext.userToken='changed';return {status:'active',sessionId,authSubject,issuer,expiresAt:null};},verifyCompanionUser:async q=>{received=q.authContext.userToken;return {verified:true,clientId:'shine.companion',shineId};}}});await f.evaluate(joined());assert.equal(received,'vault-user-secret');});
