import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCareRetryIdentityGate as create} from './veteran-care-retry-identity-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[],reads=[],registry=new Map();
  const evaluate=create({bindRetryIdentity:async q=>{const old=registry.get(q.operationId);if(old)return {status:'existing',...old};registry.set(q.operationId,q);return {status:'bound',...q};},taskClock:()=>1500000,getCurrentVCTask:async()=>task(),audienceClock:()=>1500000,verifyResultRecipient:async()=>recipient(),releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads,registry};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({operationId:sessionId,taskId:grantId,recipientAuthContext:{serviceToken:'synthetic-recipient'},authContext:input().authContext,companionAuthContext:{clientToken:'synthetic-client',userToken:'synthetic-user'},request:{operation:'read',memoryId:recordId,memoryVersion:3,preparationId}});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
const recipient=()=>({verified:true,audience:'vc-trusted-server',appId,actorShineId:shineId,servicePrincipalId:'vc-orchestrator',revision:1,validUntil:end});
const task=()=>({taskId:grantId,foundationAppId:appId,ownerShineId:shineId,memoryId:recordId,memoryVersion:3,preparationId,purpose,operation:'read',status:'running',revision:1,validUntil:end});
test('exact retry retains operation identity while rechecking current authority',async()=>{const f=fixture(),a=await f.evaluate(joined()),b=await f.evaluate(joined());assert.equal(a.status,'retry-bound-result');assert.equal(b.status,'retry-bound-result');assert.equal(a.retry.operationId,b.retry.operationId);assert.equal(a.retry.fingerprint,b.retry.fingerprint);assert.equal(a.retry.identityReused,false);assert.equal(b.retry.identityReused,true);assert.equal(b.retry.authorityRechecked,true);assert.equal(b.retry.resultReused,false);assert.equal(f.reads.length,2);assert.ok(Object.isFrozen(b.retry));assert.match(b.retry.fingerprint,/^[0-9a-f]{64}$/);});
test('same operation cannot change task memory version or preparation',async()=>{for(const change of [q=>q.taskId=recordId,q=>q.request.memoryId=preparationId,q=>q.request.memoryVersion=4,q=>q.request.preparationId=recordId]){const f=fixture();await f.evaluate(joined());const q=joined();change(q);assert.equal((await f.evaluate(q)).result,undefined);assert.equal(f.reads.length,1);}});
test('same operation cannot cross authenticated owners',async()=>{let actor=shineId;const f=fixture({options:{verifyIdentity:async()=>({shineId:actor,authSubject,providerId:'supabase:veteran-care'})}});await f.evaluate(joined());actor=recordId;assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,1);});
test('credential refresh preserves scope identity without caching authority',async()=>{const f=fixture(),a=await f.evaluate(joined()),q=joined();q.companionAuthContext.userToken='refreshed';q.recipientAuthContext.serviceToken='refreshed-service';const b=await f.evaluate(q);assert.equal(b.status,'retry-bound-result');assert.equal(a.retry.fingerprint,b.retry.fingerprint);const stored=JSON.stringify([...f.registry.values()]);assert.equal(stored.includes('refreshed'),false);assert.equal(stored.includes('synthetic'),false);assert.equal(stored.includes('content'),false);});
test('cancelled task or revoked memory consent defeats previously bound retry',async()=>{for(const kind of ['task','consent']){let withdrawn=false;const f=fixture({options:{getCurrentVCTask:async()=>({...task(),status:withdrawn&&kind==='task'?'cancelled':'running'}),getMemoryPermissionContext:async()=>({...consent(),grants:withdrawn&&kind==='consent'?[]:[memoryGrant()]})}});await f.evaluate(joined());withdrawn=true;assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,1);}});
test('registry outage mismatched acknowledgement and forged binding stop before read',async()=>{for(const bindRetryIdentity of [async()=>{throw Error('private');},async q=>({status:'existing',...q,fingerprint:'wrong'}),async q=>({status:'bound',...q,operationId:recordId}),async q=>({status:'existing',...q,binding:{...q.binding,actorShineId:recordId}})]){const f=fixture({options:{bindRetryIdentity}}),r=await f.evaluate(joined());assert.equal(r.result,undefined);assert.equal(f.reads.length,0);assert.equal(JSON.stringify(r).includes('private'),false);}});
test('result is freshly read rather than replaying stored content',async()=>{let content='first';const f=fixture({options:{readSelectedMemory:async()=>({...row(),content})}});const a=await f.evaluate(joined());content='second';const b=await f.evaluate(joined());assert.equal(a.result.content,'first');assert.equal(b.result.content,'second');assert.equal(b.retry.resultReused,false);});
test('input authority flags writes and accessors cannot define retry identity',async()=>{for(const change of [q=>q.fingerprint='trusted',q=>q.replayed=true,q=>q.request.operation='write',q=>Object.defineProperty(q,'operationId',{get(){throw Error('getter');}})]){const f=fixture(),q=joined();change(q);assert.equal((await f.evaluate(q)).result,undefined);assert.equal(f.registry.size,0);}});
test('scope and operation input are captured before async verification',async()=>{const q=joined(),pending=fixture().evaluate(q);q.operationId=recordId;q.request.memoryId=preparationId;const r=await pending;assert.equal(r.retry.operationId,sessionId);assert.equal(r.result.memoryId,recordId);});
test('concurrent exact retries share one immutable registry binding and recheck independently',async()=>{const f=fixture(),results=await Promise.all([f.evaluate(joined()),f.evaluate(joined())]);assert.deepEqual(results.map(r=>r.status),['retry-bound-result','retry-bound-result']);assert.equal(f.registry.size,1);assert.deepEqual(results.map(r=>r.retry.identityReused).sort(),[false,true]);assert.equal(f.reads.length,2);});
