import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCareMemoryScopeEvaluator as create} from './veteran-care-memory-scope-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[];
  const evaluate=create({memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({authContext:input().authContext,companionAuthContext:{clientToken:'synthetic-client',userToken:'synthetic-user'},request:{operation:'read',memoryId:recordId,memoryVersion:3,preparationId}});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
test('exact selected memory consent joins same-user L link and purpose',async()=>{const f=fixture(),r=await f.evaluate(joined());assert.equal(r.status,'memory-scope-allowed');assert.equal(r.envelope.memoryId,recordId);assert.equal(r.envelope.memoryVersion,3);assert.equal(r.envelope.permissionRevision,1);assert.equal(r.envelope.validUntil,end);assert.equal(r.executionPermitted,false);assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.memoryWritePermitted,false);assert.ok(Object.isFrozen(r.envelope));assert.equal(f.calls.length,2);assert.equal(JSON.stringify(r).includes('synthetic'),false);});
test('approved link and record consent without separate memory grant deny',async()=>{for(const grants of [[],[grant()]])assert.equal((await fixture({options:{getMemoryPermissionContext:async()=>({...consent(),grants})}}).evaluate(joined())).envelope,undefined);});
test('writes broad searches owner overrides and accessors stop before authority',async()=>{for(const change of [q=>q.request.operation='write',q=>q.request.memoryId='*',q=>q.request.query='all',q=>q.request.ownerShineId=shineId,q=>Object.defineProperty(q.request,'memoryId',{get(){throw Error('getter');}})]){let reads=0;const q=joined();change(q);const r=await fixture({options:{getMemoryDescriptor:async()=>{reads++;}}}).evaluate(q);assert.equal(r.envelope,undefined);assert.equal(reads,0);}});
test('memory owner version category and availability must match selected item',async()=>{for(const [key,value] of [['ownerShineId',sessionId],['memoryVersion',4],['category','family'],['status','deleted'],['memoryId',preparationId]]){const r=await fixture({options:{getMemoryDescriptor:async()=>({...memory(),[key]:value})}}).evaluate(joined());assert.equal(r.envelope,undefined);}});
test('purpose preparation belongs to same owner and approved VC purpose',async()=>{for(const [key,value] of [['ownerShineId',sessionId],['preparationId',recordId],['purpose','general-chat'],['status','cancelled']])assert.equal((await fixture({options:{getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose,[key]:value})}}).evaluate(joined())).envelope,undefined);});
test('grant scope client link revision exact memory and purpose cannot broaden',async()=>{for(const [key,value] of [['scope','*'],['clientId','shine.travel'],['linkRevision',2],['linkId',recordId],['memoryId',preparationId],['memoryVersion',4],['purpose','general-chat'],['preparationId',recordId],['operation','write'],['status','revoked']]){const c=consent();c.grants[0][key]=value;assert.equal((await fixture({options:{getMemoryPermissionContext:async()=>c}}).evaluate(joined())).envelope,undefined);}});
test('incomplete stale and duplicate matching grants deny',async()=>{for(const c of [{...consent(),complete:false},{...consent(),revision:0},{...consent(),grants:[memoryGrant(),memoryGrant()]}])assert.equal((await fixture({options:{getMemoryPermissionContext:async()=>c}}).evaluate(joined())).envelope,undefined);});
test('withdrawn or changed L link during memory evaluation defeats initial binding',async()=>{for(const change of [r=>r.status='revoked',r=>r.revision=2]){let reads=0;assert.equal((await fixture({options:{getCurrentVCCompanionLink:async()=>{const r=link();if(reads++)change(r);return r;}}}).evaluate(joined())).envelope,undefined);}});
test('consent deadlines cannot be extended and expiry at final boundary denies',async()=>{for(const change of [g=>g.expiresAt='1970-01-01T00:40:00.000Z',g=>{g.notBefore=end;g.consentStartsAt=end;}]){const c=consent();change(c.grants[0]);assert.equal((await fixture({options:{getMemoryPermissionContext:async()=>c}}).evaluate(joined())).envelope,undefined);}let clock=1500000;const f=fixture({options:{memoryClock:()=>clock,getCurrentMemoryPermissionRevision:async()=>{clock=2000000;return revision();}}});assert.equal((await f.evaluate(joined())).envelope,undefined);});
test('grant snapshot is immutable across revision wait and dependency outages fail closed',async()=>{const c=consent();c.grants[0].status='revoked';const f=fixture({options:{getMemoryPermissionContext:async()=>c,getCurrentMemoryPermissionRevision:async()=>{c.grants[0].status='active';return revision();}}});assert.equal((await f.evaluate(joined())).envelope,undefined);for(const key of ['getMemoryDescriptor','getMemoryPermissionContext','getCurrentMemoryPermissionRevision'])assert.equal((await fixture({options:{[key]:async()=>{throw Error('private');}}}).evaluate(joined())).status,'unavailable');});
test('memory withdrawal revision during final link recheck invalidates consent snapshot',async()=>{let calls=0;const f=fixture({options:{getCurrentMemoryPermissionRevision:async()=>({...revision(),revision:++calls===1?1:2})}});assert.equal((await f.evaluate(joined())).envelope,undefined);assert.equal(calls,2);});
test('selected memory input is captured before async identity verification',async()=>{const q=joined(),pending=fixture().evaluate(q);q.request.memoryId=preparationId;q.request.memoryVersion=9;const r=await pending;assert.equal(r.status,'memory-scope-allowed');assert.equal(r.envelope.memoryId,recordId);assert.equal(r.envelope.memoryVersion,3);});
