import test from 'node:test';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {createVeteranCareCapabilityHealthGate as create,VETERAN_CARE_READ_HEALTH_DEPENDENCIES as deps} from './veteran-care-capability-health-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const healthCalls=[];const refs=[],resolutions=[];const calls=[],reads=[],registry=new Map([[sessionId,retryRow()]]);
  const evaluate=create({healthClock:()=>1500000,getCurrentVCCapabilityHealth:async q=>{healthCalls.push(q);return health(q);},credentialClock:()=>1500000,getCurrentCredentialReference:async q=>{refs.push(q);return reference();},resolveCredentialReference:async q=>{resolutions.push(q);return credentials();},resumeClock:()=>1500000,getCurrentResumeCheckpoint:async()=>checkpoint(),getExistingRetryIdentity:async q=>registry.get(q.operationId),taskClock:()=>1500000,getCurrentVCTask:async()=>task(),audienceClock:()=>1500000,verifyResultRecipient:async()=>recipient(),releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads,registry,refs,resolutions,healthCalls};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({checkpointId:preparationId,credentialReferenceId:grantId,authContext:input().authContext});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
const recipient=()=>({verified:true,audience:'vc-trusted-server',appId,actorShineId:shineId,servicePrincipalId:'vc-orchestrator',revision:1,validUntil:end});
const task=()=>({taskId:grantId,foundationAppId:appId,ownerShineId:shineId,memoryId:recordId,memoryVersion:3,preparationId,purpose,operation:'read',status:'running',revision:1,validUntil:end});
const checkpoint=()=>({checkpointId:preparationId,foundationAppId:appId,ownerShineId:shineId,operationId:sessionId,taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,stage:'selected-memory-read',status:'resumable',revision:1,validUntil:end});
function retryRow(){const binding={foundationAppId:appId,actorShineId:shineId,clientId:'shine.companion',taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,operation:'read',scope:'veteran-care.memory.read',purpose,audience:'vc-trusted-server'};return {operationId:sessionId,fingerprint:createHash('sha256').update(JSON.stringify(binding)).digest('hex'),binding};}
const reference=()=>({credentialReferenceId:grantId,foundationAppId:appId,ownerShineId:shineId,purpose:'veteran-care.resume',audience:'vc-trusted-server',status:'active',revision:1,validUntil:end});
const credentials=()=>({credentialReferenceId:grantId,revision:1,companionAuthContext:{clientToken:'vault-client-secret',userToken:'vault-user-secret'},recipientAuthContext:{serviceToken:'vault-service-secret'}});
const observed='1970-01-01T00:24:00.000Z';
const health=q=>({...q,healthStatus:'available',lastOutcome:'success',lastEventAt:observed,evidenceRef:sessionId,evidenceMode:'synthetic'});
test('all route dependencies require fresh successful evidence alongside actual authority',async()=>{const f=fixture(),r=await f.evaluate(joined());assert.equal(r.status,'capability-health-checked-result');assert.equal(r.capabilityHealth.authorityProvided,false);assert.equal(r.requiresFreshCapabilityHealthCheck,true);assert.deepEqual(r.capabilityHealth.dependencies.map(x=>x.dependencyId),deps);assert.equal(r.capabilityHealth.dependencies.every(x=>x.evidenceMode==='synthetic'),true);assert.equal(f.healthCalls.length,deps.length*3);assert.equal(f.reads.length,1);assert.ok(f.healthCalls.every(Object.isFrozen));assert.ok(Object.isFrozen(r.capabilityHealth.dependencies));assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.transportPerformed,false);assert.equal(JSON.stringify(f.healthCalls).includes('secret'),false);});
test('every individual failed or unknown dependency blocks resolution and private retrieval',async()=>{for(const dependency of deps){const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),healthStatus:q.dependencyId===dependency?'unknown':'available'})}});assert.equal((await f.evaluate(joined())).status,'unavailable');assert.equal(f.resolutions.length,0);assert.equal(f.reads.length,0);}});
test('quarantine failure stale missing future and malformed evidence never imply health',async()=>{for(const update of [{healthStatus:'quarantined'},{lastOutcome:'failure'},{lastEventAt:'1970-01-01T00:20:00.000Z'},{lastEventAt:null},{lastEventAt:'1970-01-01T00:26:00.000Z'},{lastEventAt:'bad'},{evidenceMode:'certified'},{evidenceRef:'secret-url'}]){const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),...update})}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('wrong app capability dependency extra fields and accessors refuse health',async()=>{for(const change of [r=>({...r,foundationAppId:'shine.travel'}),r=>({...r,capabilityId:'veteran-care.write'}),r=>({...r,dependencyId:'host-ping'}),r=>({...r,permission:'allow'}),r=>({...r,get lastEventAt(){throw Error('getter');}}),()=>null]){const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>change(health(q))}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('healthy infrastructure cannot bypass session L user consent cancellation or recipient authority',async()=>{for(const options of [{getSessionState:async()=>({status:'revoked'})},{verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId:recordId})},{getMemoryPermissionContext:async()=>({...consent(),grants:[]})},{getCurrentVCTask:async()=>({...task(),status:'cancelled'})},{verifyResultRecipient:async()=>({...recipient(),audience:'shine.ai'})}]){const f=fixture({options});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('health deterioration immediately before private read prevents invocation',async()=>{let n=0;const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),healthStatus:n++>=deps.length?'quarantined':'available'})}}),r=await f.evaluate(joined());assert.equal(r.retrievalPerformed,false);assert.equal(r.result,undefined);assert.equal(f.reads.length,0);});
test('health failure after private read withholds prepared result',async()=>{let n=0;const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),lastOutcome:n++>=deps.length*2?'failure':'success'})}}),r=await f.evaluate(joined());assert.equal(r.retrievalPerformed,true);assert.equal(r.result,undefined);});
test('exact freshness boundary blocks while one millisecond inside bounds result deadline',async()=>{const r=await fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),lastEventAt:new Date(1200001).toISOString()})}}).evaluate(joined());assert.equal(r.recipient.validUntil,new Date(1500001).toISOString());assert.equal(r.credentialReference.validUntil,r.recipient.validUntil);const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),lastEventAt:new Date(1200000).toISOString()})}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);});
test('whole sweep rechecks expiry and clock regression or invalid time refuses evidence',async()=>{for(const time of [NaN,1499999,1740000]){let t=1500000,n=0;const f=fixture({options:{healthClock:()=>t,getCurrentVCCapabilityHealth:async q=>{if(n++>=deps.length-1)t=time;return health(q);}}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('current health evidence may refresh and modes remain explicit without claimed authority',async()=>{let n=0;const f=fixture({options:{getCurrentVCCapabilityHealth:async q=>({...health(q),lastEventAt:new Date(1440000+n++).toISOString(),evidenceMode:q.dependencyId==='vc-session'?'live':'synthetic'})}}),r=await f.evaluate(joined());assert.equal(r.status,'capability-health-checked-result');assert.equal(r.capabilityHealth.dependencies[0].evidenceMode,'live');assert.equal(r.capabilityHealth.dependencies[1].evidenceMode,'synthetic');assert.equal(r.capabilityHealth.authorityProvided,false);});
test('caller green status write requests and altered reference input cannot supply health',async()=>{for(const change of [q=>q.healthStatus='available',q=>q.request={operation:'write'},q=>q.capabilityId='other',q=>Object.defineProperty(q,'credentialReferenceId',{get(){throw Error('getter');}})]){const f=fixture(),q=joined();change(q);assert.equal((await f.evaluate(q)).result,undefined);assert.equal(f.healthCalls.length,0);}const f=fixture(),q=joined(),pending=f.evaluate(q);q.credentialReferenceId=recordId;assert.equal((await pending).credentialReference.credentialReferenceId,grantId);});
test('health adapter outages fail closed and redact private details',async()=>{const f=fixture({options:{getCurrentVCCapabilityHealth:async()=>{throw Error('private-host-secret');}}}),r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.result,undefined);assert.equal(JSON.stringify(r).includes('secret'),false);assert.equal(f.reads.length,0);});
