import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCareAICallerBinder as create} from './veteran-care-ai-caller-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const appId='shine.veteran-care',sessionId='33333333-3333-4333-8333-333333333333';
const identity={shineId:'11111111-1111-4111-8111-111111111111',authSubject:'22222222-2222-4222-8222-222222222222',providerId:'supabase:veteran-care'};
const configuration={mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url};
const claims=()=>({iss:issuer,aud:'authenticated',role:'authenticated',sub:identity.authSubject,session_id:sessionId,exp:2000});
const state=()=>({status:'active',sessionId,authSubject:identity.authSubject,issuer,expiresAt:null});
const proofRef='44444444-4444-4444-8444-444444444444';
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},aiCallerProof:{proofRef}});
const registration=()=>({foundationAppId:appId,aiCallerId:'shine-veteran-care',targetServiceAppId:'shine.ai',status:'active',revision:1,keyId:'vc-adj-v1'});
function fixture({row=registration(),change=()=>{},session=state(),resolve,registry}={}){const calls=[];return {calls,bind:create({configuration,appId,providerId:identity.providerId,clock:()=>1000000,auth:{getClaims:async()=>({data:{claims:claims()}})},verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>identity,getSessionState:async()=>session,
 getAICallerRegistration:async q=>{calls.push(q);return registry?registry(q):row;},resolveVerifiedAICallerProof:async q=>{calls.push(q);if(resolve)return resolve(q);const p={verified:true,proofRef:q.proofRef,foundationAppId:appId,actorShineId:identity.shineId,appId:'shine-veteran-care',keyId:'vc-adj-v1'};change(p);return p;}})};}
test('exact Foundation VC principal binds independently verified dedicated AI caller without execution',async()=>{const f=fixture(),r=await f.bind(input());assert.equal(r.status,'caller-bound');assert.equal(r.executionPermitted,false);assert.equal(r.binding.aiCallerId,'shine-veteran-care');assert.equal(r.binding.foundationAppId,appId);assert.ok(Object.isFrozen(r.binding));assert.equal(JSON.stringify(f.calls).includes('synthetic'),false);assert.equal(JSON.stringify(r).includes('c2ln'),false);});
test('borrowed caller revoked registration wrong service and malformed key cannot reach proof',async()=>{for(const [key,value] of [['aiCallerId','shine-fish'],['foundationAppId','shine.wellness'],['targetServiceAppId','shine.other'],['status','revoked'],['revision',0],['keyId','*']]){const f=fixture({row:{...registration(),[key]:value}});assert.equal((await f.bind(input())).status,'denied');assert.equal(f.calls.length,1);}});
test('proof must match actor app key handle and Foundation principal exactly',async()=>{for(const [key,value] of [['verified',false],['proofRef',sessionId],['actorShineId',proofRef],['foundationAppId','shine.other'],['appId','shine-fish'],['keyId',null],['keyId','other-key']]){const r=await fixture({change:p=>p[key]=value}).bind(input());assert.equal(r.status,'denied');assert.equal(r.binding,undefined);}});
test('opaque handle alone missing proof or authority outage cannot create binding',async()=>{for(const resolve of [async()=>null,async()=>({proofRef,verified:true}),async()=>{throw Error('secret');}]){const r=await fixture({resolve}).bind(input());assert.notEqual(r.status,'caller-bound');assert.equal(JSON.stringify(r).includes('secret'),false);}});
test('revoked session stops before registration and caller input cannot select AI identity',async()=>{const f=fixture({session:null});assert.equal((await f.bind(input())).status,'denied');assert.equal(f.calls.length,0);const g=fixture(),i=input();i.aiCallerProof.appId='shine-fish';assert.equal((await g.bind(i)).status,'denied');assert.equal(g.calls.length,0);});
test('captured registration and caller handle survive mutation during awaits',async()=>{const row=registration(),f=fixture({row,resolve:async q=>{row.keyId='other-key';return {verified:true,proofRef:q.proofRef,foundationAppId:appId,actorShineId:identity.shineId,appId:'shine-veteran-care',keyId:'vc-adj-v1'};}}),i=input(),pending=f.bind(i);i.aiCallerProof.proofRef=sessionId;i.authContext.jwt='changed';const r=await pending;assert.equal(r.status,'caller-bound');assert.equal(r.binding.keyId,'vc-adj-v1');assert.equal(r.binding.proofRef,proofRef);});
test('accessor input is refused without invoking it',async()=>{const f=fixture(),i=input();Object.defineProperty(i.aiCallerProof,'proofRef',{get(){throw Error('do not call');}});assert.equal((await f.bind(i)).status,'denied');assert.equal(f.calls.length,0);});
