import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCareTaskAuthorityGate as create} from './veteran-care-task-authority-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[],reads=[];
  const evaluate=create({taskClock:()=>1500000,getCurrentVCTask:async()=>task(),audienceClock:()=>1500000,verifyResultRecipient:async()=>recipient(),releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({taskId:grantId,recipientAuthContext:{serviceToken:'synthetic-recipient'},authContext:input().authContext,companionAuthContext:{clientToken:'synthetic-client',userToken:'synthetic-user'},request:{operation:'read',memoryId:recordId,memoryVersion:3,preparationId}});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
const recipient=()=>({verified:true,audience:'vc-trusted-server',appId,actorShineId:shineId,servicePrincipalId:'vc-orchestrator',revision:1,validUntil:end});
const task=()=>({taskId:grantId,foundationAppId:appId,ownerShineId:shineId,memoryId:recordId,memoryVersion:3,preparationId,purpose,operation:'read',status:'running',revision:1,validUntil:end});
test('current running task binds exact private result without transport',async()=>{let checks=0;const f=fixture({options:{getCurrentVCTask:async()=>{checks++;return task();}}}),r=await f.evaluate(joined());assert.equal(r.status,'task-bound-result');assert.equal(r.task.taskId,grantId);assert.equal(r.task.revision,1);assert.equal(r.task.validUntil,end);assert.equal(r.requiresFreshTaskCheck,true);assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.transportPerformed,false);assert.ok(Object.isFrozen(r.task));assert.equal(r.result.content,'synthetic private memory');assert.equal(checks,3);assert.equal(f.reads.length,1);});
test('cancelled superseded completed queued and missing tasks stop before content',async()=>{for(const status of ['cancelled','superseded','completed','queued']){const f=fixture({options:{getCurrentVCTask:async()=>({...task(),status})}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}assert.equal((await fixture({options:{getCurrentVCTask:async()=>null}}).evaluate(joined())).result,undefined);});
test('wrong owner app memory version purpose preparation or revision cannot borrow task',async()=>{for(const [key,value] of [['ownerShineId',sessionId],['foundationAppId','shine.travel'],['memoryId',preparationId],['memoryVersion',4],['preparationId',recordId],['purpose','general-chat'],['operation','write'],['revision',0],['taskId',recordId]]){const f=fixture({options:{getCurrentVCTask:async()=>({...task(),[key]:value})}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('cancellation while recipient and memory checks await prevents actual read',async()=>{let checks=0;const f=fixture({options:{getCurrentVCTask:async()=>({...task(),status:checks++?'cancelled':'running'})}});const r=await f.evaluate(joined());assert.equal(r.status,'denied');assert.equal(r.retrievalPerformed,false);assert.equal(f.reads.length,0);assert.equal(r.result,undefined);});
test('cancellation during content retrieval withholds prepared result',async()=>{let cancelled=false;const f=fixture({options:{getCurrentVCTask:async()=>({...task(),status:cancelled?'cancelled':'running'}),readSelectedMemory:async()=>{cancelled=true;return row();}}});const r=await f.evaluate(joined());assert.equal(r.status,'denied');assert.equal(r.retrievalPerformed,true);assert.equal(r.result,undefined);});
test('changed running task revision or deadline cannot inherit previous authority',async()=>{for(const [key,value] of [['revision',2],['validUntil','1970-01-01T00:32:00.000Z']]){let checks=0;const f=fixture({options:{getCurrentVCTask:async()=>({...task(),...(checks++>=2?{[key]:value}:{})})}});assert.equal((await f.evaluate(joined())).result,undefined);}});
test('retry of same cancelled task performs no additional private read',async()=>{let cancelled=false,reads=0;const f=fixture({options:{getCurrentVCTask:async()=>({...task(),status:cancelled?'cancelled':'running'}),readSelectedMemory:async()=>{reads++;cancelled=true;return row();}}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(reads,1);});
test('task deadline bounds result expiry and clock regression fails closed',async()=>{const validUntil='1970-01-01T00:30:00.000Z';assert.equal((await fixture({options:{getCurrentVCTask:async()=>({...task(),validUntil})}}).evaluate(joined())).task.validUntil,validUntil);for(const late of [2000000,1499999,NaN]){let clock=1500000,checks=0;const f=fixture({options:{taskClock:()=>clock,getCurrentVCTask:async()=>{if(checks++)clock=late;return task();}}});assert.equal((await f.evaluate(joined())).result,undefined);}});
test('task authority outage and accessors withhold content without private errors',async()=>{for(const getCurrentVCTask of [async()=>{throw Error('private');},async()=>Object.defineProperty(task(),'status',{get(){throw Error('getter');}})]){const f=fixture({options:{getCurrentVCTask}}),r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.result,undefined);assert.equal(f.reads.length,0);assert.equal(JSON.stringify(r).includes('private'),false);}});
test('caller status revision and task mutation cannot override current authority',async()=>{for(const change of [q=>q.status='running',q=>q.revision=1,q=>q.task={...task()},q=>q.request.operation='write']){const q=joined();change(q);const f=fixture();assert.equal((await f.evaluate(q)).result,undefined);assert.equal(f.reads.length,0);}const q=joined(),pending=fixture().evaluate(q);q.taskId=recordId;q.request.memoryId=preparationId;const r=await pending;assert.equal(r.task.taskId,grantId);assert.equal(r.result.memoryId,recordId);});
