import test from 'node:test';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {createVeteranCareResumeRecheckGate as create} from './veteran-care-resume-recheck-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[],reads=[],registry=new Map([[sessionId,retryRow()]]);
  const evaluate=create({resumeClock:()=>1500000,getCurrentResumeCheckpoint:async()=>checkpoint(),getExistingRetryIdentity:async q=>registry.get(q.operationId),taskClock:()=>1500000,getCurrentVCTask:async()=>task(),audienceClock:()=>1500000,verifyResultRecipient:async()=>recipient(),releaseClock:()=>1500000,readSelectedMemory:async q=>{reads.push(q);return row();},memoryClock:()=>1500000,getMemoryDescriptor:async()=>memory(),getMemoryPermissionContext:async()=>consent(),getCurrentMemoryPermissionRevision:async()=>revision(),bindingClock:()=>1500000,verifyIntegrationClient:async()=>({clientId:'shine.companion',clientKind:'first-party-companion'}),verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId}),getCurrentVCCompanionLink:async q=>{calls.push(q);return link();},appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {evaluate,calls,reads,registry};
}
const link=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,status:'active',revision:1,validUntil:end});
const joined=()=>({checkpointId:preparationId,recipientAuthContext:{serviceToken:'synthetic-recipient'},authContext:input().authContext,companionAuthContext:{clientToken:'synthetic-client',userToken:'synthetic-user'}});
const memory=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',status:'available'});
const revision=()=>({foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,revision:1});
const memoryGrant=()=>({grantId,status:'active',foundationAppId:appId,clientId:'shine.companion',ownerShineId:shineId,linkId:sessionId,linkRevision:1,memoryId:recordId,memoryVersion:3,scope:'veteran-care.memory.read',operation:'read',purpose,preparationId,notBefore:start,expiresAt:end,consentStartsAt:start,consentExpiresAt:end});
const consent=()=>({complete:true,revision:1,grants:[memoryGrant()]});
const row=()=>({memoryId:recordId,memoryVersion:3,ownerShineId:shineId,category:'veteran-care.context',content:'synthetic private memory'});
const recipient=()=>({verified:true,audience:'vc-trusted-server',appId,actorShineId:shineId,servicePrincipalId:'vc-orchestrator',revision:1,validUntil:end});
const task=()=>({taskId:grantId,foundationAppId:appId,ownerShineId:shineId,memoryId:recordId,memoryVersion:3,preparationId,purpose,operation:'read',status:'running',revision:1,validUntil:end});
const checkpoint=()=>({checkpointId:preparationId,foundationAppId:appId,ownerShineId:shineId,operationId:sessionId,taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,stage:'selected-memory-read',status:'resumable',revision:1,validUntil:end});
function retryRow(){const binding={foundationAppId:appId,actorShineId:shineId,clientId:'shine.companion',taskId:grantId,memoryId:recordId,memoryVersion:3,preparationId,operation:'read',scope:'veteran-care.memory.read',purpose,audience:'vc-trusted-server'};return {operationId:sessionId,fingerprint:createHash('sha256').update(JSON.stringify(binding)).digest('hex'),binding};}
test('resume uses server checkpoint selection and existing operation with fresh authority',async()=>{const f=fixture(),r=await f.evaluate(joined());assert.equal(r.status,'resume-rechecked-result');assert.equal(r.checkpoint.checkpointId,preparationId);assert.equal(r.retry.operationId,sessionId);assert.equal(r.retry.identityReused,true);assert.equal(r.retry.authorityRechecked,true);assert.equal(r.checkpointAuthorityReused,false);assert.equal(r.modelDisclosurePermitted,false);assert.equal(r.transportPerformed,false);assert.ok(Object.isFrozen(r.checkpoint));assert.equal(f.reads.length,1);});
test('missing corrupt completed superseded or wrong-stage checkpoints never read',async()=>{for(const row of [null,{}, {...checkpoint(),status:'completed'},{...checkpoint(),status:'superseded'},{...checkpoint(),stage:'model-disclosure'},{...checkpoint(),revision:0}]){const f=fixture({options:{getCurrentResumeCheckpoint:async()=>row}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('checkpoint owner app and changed selection cannot borrow old retry identity',async()=>{for(const [key,value] of [['ownerShineId',sessionId],['foundationAppId','shine.travel'],['memoryId',preparationId],['memoryVersion',4],['preparationId',recordId],['taskId',recordId],['operationId',recordId]]){const f=fixture({options:{getCurrentResumeCheckpoint:async()=>({...checkpoint(),[key]:value})}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('lost or mismatched retry identity cannot be reconstructed from checkpoint',async()=>{for(const getExistingRetryIdentity of [async()=>null,async()=>({...retryRow(),fingerprint:'wrong'}),async()=>({...retryRow(),binding:{...retryRow().binding,actorShineId:sessionId}})]){const f=fixture({options:{getExistingRetryIdentity}});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('saved checkpoint cannot bypass cancelled task withdrawn consent or changed L user',async()=>{for(const options of [{getCurrentVCTask:async()=>({...task(),status:'cancelled'})},{getMemoryPermissionContext:async()=>({...consent(),grants:[]})},{verifyCompanionUser:async()=>({verified:true,clientId:'shine.companion',shineId:sessionId})}]){const f=fixture({options});assert.equal((await f.evaluate(joined())).result,undefined);assert.equal(f.reads.length,0);}});
test('checkpoint withdrawal before actual read suppresses adapter invocation',async()=>{let checks=0;const f=fixture({options:{getCurrentResumeCheckpoint:async()=>({...checkpoint(),status:checks++?'superseded':'resumable'})}});const r=await f.evaluate(joined());assert.equal(r.result,undefined);assert.equal(r.retrievalPerformed,false);assert.equal(f.reads.length,0);});
test('checkpoint revision change during read withholds prepared content',async()=>{let checks=0;const f=fixture({options:{getCurrentResumeCheckpoint:async()=>({...checkpoint(),revision:checks++>=2?2:1})}});const r=await f.evaluate(joined());assert.equal(r.result,undefined);assert.equal(r.retrievalPerformed,true);});
test('checkpoint expiry bounds deadline and expiry or clock regression during checks deny',async()=>{const validUntil='1970-01-01T00:30:00.000Z';assert.equal((await fixture({options:{getCurrentResumeCheckpoint:async()=>({...checkpoint(),validUntil})}}).evaluate(joined())).checkpoint.validUntil,validUntil);for(const late of [2000000,1499999,NaN]){let clock=1500000,checks=0;const f=fixture({options:{resumeClock:()=>clock,getCurrentResumeCheckpoint:async()=>{if(checks++)clock=late;return checkpoint();}}});assert.equal((await f.evaluate(joined())).result,undefined);}});
test('caller selection cached authority results and accessors are refused',async()=>{for(const change of [q=>q.request={operation:'read',memoryId:recordId},q=>q.operationId=sessionId,q=>q.permission={decision:'allow'},q=>q.result=row(),q=>Object.defineProperty(q,'checkpointId',{get(){throw Error('getter');}})]){const q=joined();change(q);const f=fixture();assert.equal((await f.evaluate(q)).result,undefined);assert.equal(f.reads.length,0);}const q=joined(),pending=fixture().evaluate(q);q.checkpointId=recordId;assert.equal((await pending).checkpoint.checkpointId,preparationId);});
test('checkpoint and registry outages reveal no private details and grant no reads',async()=>{for(const key of ['getCurrentResumeCheckpoint','getExistingRetryIdentity']){const f=fixture({options:{[key]:async()=>{throw Error('private');}}}),r=await f.evaluate(joined());assert.equal(r.status,'unavailable');assert.equal(r.result,undefined);assert.equal(JSON.stringify(r).includes('private'),false);assert.equal(f.reads.length,0);}});
