import test from 'node:test';
import assert from 'node:assert/strict';
import {createVeteranCarePrivateHandleService as create} from './veteran-care-private-handle-v1.mjs';
import {VETERAN_CARE_ISSUER as issuer} from './veteran-care-identity-v1.mjs';
import {VETERAN_CARE_PROJECT_URL as url} from './veteran-care-project-boundary-v1.mjs';
const start='1970-01-01T00:16:40.000Z',end='1970-01-01T00:33:20.000Z';
const timed=()=>({notBefore:start,expiresAt:end,consentWindow:{startsAt:start,expiresAt:end}});
const appId='shine.veteran-care',recordId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',preparationId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',grantId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const shineId='11111111-1111-4111-8111-111111111111',authSubject='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333';
const purpose='veteran-care.appointment-preparation',scope='veteran-care.record.read',resourceCategory='veteran-care.record';
const grant=()=>({grantId,appId,ownerShineId:shineId,scope,purpose,status:'active',resourceSelector:{resourceId:recordId,resourceVersion:3},purposeBinding:{kind:'appointment-preparation',preparationId},...timed()});
const input=()=>({authContext:{appToken:'synthetic',jwt:'e30.'+Buffer.from(JSON.stringify({iss:issuer})).toString('base64url')+'.c2ln'},request:{capabilityId:'veteran-care.selected_record_read',input:{recordId,recordVersion:3}},purposeContext:{preparationId}});
const stamp=(revision=1)=>({appId,ownerShineId:shineId,revision});
const context=()=>({complete:true,appManifest:{appId,foundation:{requestedScopes:[{scope,purpose,resourceCategory}]}},grants:[grant()],defenceDecision:'allow',permissionSnapshot:stamp()});
function fixture({snapshot=context(),current=stamp(),lookup,options={}}={}){
  const calls=[],rows=new Map();
  const evaluate=create({insertPrivateHandle:async row=>{if(rows.has(row.handleId))return {status:'conflict',handleId:row.handleId};rows.set(row.handleId,row);return {status:'inserted',handleId:row.handleId};},getPrivateHandle:async id=>rows.get(id),handleClock:()=>1500000,handleIdFactory:()=>recordId,decisionClock:()=>1500000,getAICallerRegistration:async()=>({foundationAppId:appId,aiCallerId:'shine-veteran-care',targetServiceAppId:'shine.ai',status:'active',revision:1,keyId:'vc-adj-v1'}),resolveVerifiedAICallerProof:async q=>({verified:true,proofRef:q.proofRef,foundationAppId:appId,actorShineId:shineId,appId:'shine-veteran-care',keyId:'vc-adj-v1'}),appId,providerId:'supabase:veteran-care',clock:()=>1500000,permissionClock:()=>1500000,idFactory:()=>grantId,
    configuration:{mode:'veteran_care',issuer,authProjectUrl:url,databaseProjectUrl:url,storageProjectUrl:url},
    auth:{getClaims:async()=>({data:{claims:{iss:issuer,aud:'authenticated',role:'authenticated',sub:authSubject,session_id:sessionId,exp:3000}}})},
    verifyAppCaller:async()=>({appId}),verifyIdentity:async()=>({shineId,authSubject,providerId:'supabase:veteran-care'}),
    getSessionState:async()=>({status:'active',sessionId,authSubject,issuer,expiresAt:null}),
    getResourceDescriptor:async()=>({resourceId:recordId,resourceVersion:3,ownerShineId:shineId,category:resourceCategory}),
    getPreparationContext:async()=>({status:'available',preparationId,ownerShineId:shineId,purpose}),
    getPermissionContext:async()=>snapshot,
    getCurrentPermissionRevision:async q=>{calls.push(q);return lookup?lookup(q):current;},...options});
  return {service:evaluate,calls,rows};
}
const joined=()=>({...input(),aiCallerProof:{proofRef:sessionId}});
test('opaque handle resolves only metadata after fresh authority checks',async()=>{const f=fixture(),r=await f.service.mint(joined());assert.equal(r.status,'handle-ready');assert.equal(r.handle.validUntil,'1970-01-01T00:30:00.000Z');assert.equal(JSON.stringify(r).includes(shineId),false);assert.equal(r.envelope,undefined);const resolved=await f.service.resolve({handleId:r.handle.handleId,decisionInput:joined()});assert.equal(resolved.status,'handle-resolved');assert.equal(resolved.envelope.resourceId,recordId);assert.equal(resolved.executionPermitted,false);assert.equal(resolved.modelDisclosurePermitted,false);assert.ok(Object.isFrozen(resolved.envelope));assert.equal(f.calls.length,2);});
test('handle alone and caller-supplied authority cannot resolve',async()=>{const f=fixture();await f.service.mint(joined());for(const q of [{handleId:recordId},{handleId:recordId,decisionInput:joined(),grantId},{handleId:'https://private.invalid/file',decisionInput:joined()}])assert.equal((await f.service.resolve(q)).envelope,undefined);});
test('revocation and stale current revision defeat previously minted handle',async()=>{for(const mutate of [c=>c.grants[0].status='revoked',c=>c.permissionSnapshot=stamp(2)]){const snapshot=context(),f=fixture({snapshot});await f.service.mint(joined());mutate(snapshot);const r=await f.service.resolve({handleId:recordId,decisionInput:joined()});assert.equal(r.status,'denied');assert.equal(r.envelope,undefined);}});
test('changed scope grant or registered key cannot inherit a handle',async()=>{for(const field of ['resourceId','resourceVersion','preparationId','grantId','actorShineId','audience','keyId','callerRegistrationRevision']){const f=fixture();await f.service.mint(joined());const row=f.rows.get(recordId);f.rows.set(recordId,{...row,binding:{...row.binding,[field]:'changed'}});assert.equal((await f.service.resolve({handleId:recordId,decisionInput:joined()})).envelope,undefined);}});
test('unknown handles and malformed registry rows share generic refusal',async()=>{const f=fixture();for(const row of [undefined,{},{contract:'wrong'}, {get contract(){throw Error('getter');}}]){f.rows.set(recordId,row);const r=await f.service.resolve({handleId:recordId,decisionInput:joined()});assert.equal(r.reasonCode,'vc-private-handle-unavailable');assert.equal(r.envelope,undefined);}});
test('expiry and clock regression during registry waits withhold output',async()=>{for(const late of [1800000,1499999]){let clock=1500000;const f=fixture({options:{handleClock:()=>clock}});await f.service.mint(joined());const row=f.rows.get(recordId);const g=fixture({options:{handleClock:()=>clock,getPrivateHandle:async()=>{clock=late;return row;}}});assert.equal((await g.service.resolve({handleId:recordId,decisionInput:joined()})).envelope,undefined);}});
test('insert failures collisions and expiry before acknowledgement produce no handle',async()=>{for(const insertPrivateHandle of [async()=>{throw Error('down');},async()=>({status:'inserted',handleId:sessionId}),async()=>({status:'conflict',handleId:recordId})])assert.equal((await fixture({options:{insertPrivateHandle}}).service.mint(joined())).handle,undefined);const f=fixture();assert.equal((await f.service.mint(joined())).status,'handle-ready');assert.equal((await f.service.mint(joined())).handle,undefined);let clock=1500000;const g=fixture({options:{handleClock:()=>clock,insertPrivateHandle:async row=>{clock=1800000;return {status:'inserted',handleId:row.handleId};}}});assert.equal((await g.service.mint(joined())).handle,undefined);});
test('registry failures and unverified caller never return record metadata',async()=>{const f=fixture({options:{getPrivateHandle:async()=>{throw Error('private data');}}});assert.equal((await f.service.resolve({handleId:recordId,decisionInput:joined()})).envelope,undefined);let lookups=0;const g=fixture({options:{resolveVerifiedAICallerProof:async()=>null,getPrivateHandle:async()=>{lookups++;}}});await g.service.resolve({handleId:recordId,decisionInput:joined()});assert.equal(lookups,0);});
test('factory refuses unbounded lifetimes and deterministic defaults are not required',()=>{for(const handleTtlMs of [0,300001,NaN])assert.throws(()=>fixture({options:{handleTtlMs}}));assert.throws(()=>fixture({options:{insertPrivateHandle:null}}));});
test('default generator yields distinct opaque v4 handles',async()=>{const f=fixture({options:{handleIdFactory:undefined}}),a=await f.service.mint(joined()),b=await f.service.mint(joined());assert.equal(a.status,'handle-ready');assert.equal(b.status,'handle-ready');assert.notEqual(a.handle.handleId,b.handle.handleId);assert.match(a.handle.handleId,/^[0-9a-f-]{36}$/);});
